package:
  name: srtm4
  version: "1.1.4.dev0"

source:
  git_rev: sharedlib
  git_url: https://github.com/yxqd/srtm4

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
  host:
    - python
    - libtiff
    - filelock
    - numpy
    - requests
  run:
    - python
    - libtiff
    - filelock
    - numpy
    - requests

build:
  script_env:

test:
  imports:
    - srtm4

about:
  home: 
  license:
  license_file:
