name: tests

on: [push, pull_request]

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtiff-dev pkg-config
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install srtm4
        run: |
          python -m pip install --upgrade pip
          pip install ".[test,crop]"
      - name: Run tests
        run: |
          pyproj sync -v --file us_nga_egm96_15
          pytest --cov=srtm4 --cov-report term-missing .